/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface StFlippy {
    'flipBackEvents': string;
    'flipDuration': number;
    'flipEvents': string;
    'flipTimingFunction': string;
    'isFlipped': boolean;
  }
}

declare global {


  interface HTMLStFlippyElement extends Components.StFlippy, HTMLStencilElement {}
  var HTMLStFlippyElement: {
    prototype: HTMLStFlippyElement;
    new (): HTMLStFlippyElement;
  };
  interface HTMLElementTagNameMap {
    'st-flippy': HTMLStFlippyElement;
  }
}

declare namespace LocalJSX {
  interface StFlippy {
    'flipBackEvents'?: string;
    'flipDuration'?: number;
    'flipEvents'?: string;
    'flipTimingFunction'?: string;
    'isFlipped'?: boolean;
  }

  interface IntrinsicElements {
    'st-flippy': StFlippy;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'st-flippy': LocalJSX.StFlippy & JSXBase.HTMLAttributes<HTMLStFlippyElement>;
    }
  }
}


